# GitBook configuration file
# This file should be placed in the root of your GitBook repository

# Root directory for documentation
root: ./

# Structure configuration
structure:
  readme: intro.md
  summary: SUMMARY.md

# Redirects configuration
# Maps old URLs to new URLs
redirects:
  # Main pages
  docs/intro: intro.md
  docs: intro.md
  intro: intro.md
  
  # Getting Started section
  docs/start_here: getting-started/start_here.md
  start_here: getting-started/start_here.md
  docs/about/license-doc: getting-started/license-doc.md
  
  # Tips & Tricks section
  docs/category/tips-and-tricks: tips-and-tricks/zoe_tips_and_tricks.md
  docs/tips_and_tricks/getting-started: tips-and-tricks/zoe_tips_and_tricks.md
  docs/tips_and_tricks/naming-conventions: tips-and-tricks/naming-conventions.md
  docs/tips_and_tricks/descriptions-and-synonyms: tips-and-tricks/descriptions-and-synonyms.md
  docs/tips_and_tricks/entity-drills: tips-and-tricks/entity-drills.md
  docs/tips_and_tricks/time-metrics: tips-and-tricks/time-metrics.md
  docs/tips_and_tricks/voice-commands: tips-and-tricks/voice-commands.md
  docs/tips_and_tricks/data-indexing: tips-and-tricks/data-indexing.md
  
  # Zenlytic UI section
  docs/category/using-zenlytic: zenlytic-ui/using_zenlytic.md
  docs/zenlytic_ui/using_zenlytic: zenlytic-ui/using_zenlytic.md
  docs/zenlytic_ui/zoe: zenlytic-ui/zoe.md
  docs/zenlytic_ui/exploring: zenlytic-ui/exploring.md
  docs/zenlytic_ui/settings: zenlytic-ui/data_model_editor.md
  docs/zenlytic_ui/user_attributes: zenlytic-ui/user_attributes.md
  docs/zenlytic_ui/basket_mix: zenlytic-ui/using_zenlytic.md
  docs/zenlytic_ui/explain_change: zenlytic-ui/using_zenlytic.md
  docs/zenlytic_ui/funnel: zenlytic-ui/using_zenlytic.md
  
  # Data Modeling section
  docs/category/data-modeling: data-modeling/data_modeling.md
  docs/data_modeling/data_modeling: data-modeling/data_modeling.md
  docs/data_modeling/model: data-modeling/model.md
  docs/data_modeling/dashboard: data-modeling/dashboard.md
  docs/data_modeling/topic: data-modeling/topic.md
  docs/data_modeling/view: data-modeling/view.md
  docs/data_modeling/join: data-modeling/join.md
  docs/data_modeling/set: data-modeling/set.md
  docs/data_modeling/access_grants: data-modeling/access_grants.md
  docs/data_modeling/field: data-modeling/field.md
  docs/data_modeling/dimension: data-modeling/dimension.md
  docs/data_modeling/dimension_group: data-modeling/dimension_group.md
  docs/data_modeling/measure: data-modeling/measure.md
  docs/data_modeling/field_filter: data-modeling/field_filter.md
  docs/data_modeling/formatting: data-modeling/formatting.md
  docs/data_modeling/symmetric_aggregates: data-modeling/symmetric_aggregates.md
  docs/data_modeling/table_calculation_syntax: data-modeling/table_calculation_syntax.md
  docs/data_modeling/referenceable_attributes: data-modeling/referenceable_attributes.md
  docs/data_modeling/dbt_metricflow: data-modeling/dbt_metricflow.md
  
  # Workflows section
  docs/category/workflows: workflows/getting-started.md
  docs/workflows/getting-started: workflows/getting-started.md
  docs/workflows/inputs: workflows/inputs.md
  docs/workflows/publish: workflows/publish.md
  docs/workflows/schedule-delivery: workflows/schedule-delivery.md
  docs/workflows/run-history: workflows/run-history.md
  
  # Embedding section
  docs/category/embedding: embedding/embedding_overview.md
  docs/embedding/embedding_overview: embedding/embedding_overview.md
  docs/embedding/private_embedding: embedding/private_embedding.md
  docs/embedding/signed_embedding: embedding/signed_embedding.md
  docs/embedding/permissions_in_embedding: embedding/permissions_in_embedding.md
  docs/embedding/embedding_styles: embedding/embedding_styles.md
  docs/embedding/workflows_in_embedding: embedding/workflows_in_embedding.md
  
  # Development Environment section (redirect to getting started)
  docs/category/development-environment: getting-started/start_here.md
  docs/development_environment/development_environment: getting-started/start_here.md
  docs/development_environment/cli: getting-started/start_here.md
  docs/development_environment/database_connection: getting-started/start_here.md
  docs/development_environment/git: getting-started/start_here.md
  
  # Connecting with Python section (redirect to getting started)
  docs/category/connecting-with-python: getting-started/start_here.md
  docs/connecting_with_python/getting_started_local: getting-started/start_here.md
  docs/connecting_with_python/connection_setup/connecting: getting-started/start_here.md
  docs/connecting_with_python/connection_setup/integrations: getting-started/start_here.md
  docs/connecting_with_python/project/project: getting-started/start_here.md
  docs/connecting_with_python/querying/data_model: getting-started/start_here.md
  docs/connecting_with_python/querying/queries: getting-started/start_here.md
  
  # About section (redirect to getting started)
  docs/category/about: getting-started/license-doc.md
  
  # Other pages
  docs/markdown-page: intro.md
  docs/search: intro.md 